### ISSUE TITLE
cljs-prod failed, cljs-dev is ok when use [reagent-utils "0.1.3"] (cookies/get "user")] 

### ISSUE THREAD

**Issue by pkvov** [thheller/shadow-build#14]
get a javascript error: 
Uncaught TypeError: undefined is not a function

then i changed the shadow.cljs.api -> build-prod -> :pretty-print true

find that the Ls function is missing
function Us() {
Ls("user");
return ib(Qp(je));
}
;

**Comment by thheller** [comment]
Do you have the source snippet? Are your sure you got the correct location? It looks like you are doing:

```clojure
(defn a-fn []
  (cookies/get "user")
  some-other-stuff)
```

Why would you ignore the return value of ```cookies/get```? Errors like these usually happen because Closure decided to rename a value that it shouldn't have, meaning you are most likely missing an externs file. The closure library itself doesn't require externs though, can't tell without more information.

**Comment by pkvov** [comment]
finally, i  use google closure cookies library directly

(defn get-cookies [name & default]
  (.get cookies name default))

thanks a alot
