### ISSUE TITLE
clj->js crushed in  prod mod

### ISSUE THREAD

**Issue by pkvov** [thheller/shadow-build#19]
(.scrollspy (js/jQuery "body") (clj->js {:target ".navbar-fixed-top"})) 
same as (.scrollspy (js/jQuery "body") #js {:target ".navbar-fixed-top"}) 

in dev mod, it's OK.  but in prod mod i got a error 

Uncaught TypeError: undefined is not a functionappointment.js:141 (anonymous function)(index):192 (anonymous function)

return jQuery("body").Kf(Ih(new s(null,1,[sm,".navbar-fixed-top"],null)))});

**Comment by thheller** [comment]
The error is not in ```clj->js``` but the ```jQuery("body").scrollspy``` function which gets renamed to  ```jQuery("body").Kf``` since I guess it is missing from the externs. Generally I would advise against using jQuery at all since most (probably more) functionality is present in the Closure Library, it is just a bit harder to find.

Otherwise you'll need to write externs for the scrollspy addon.

**Comment by pkvov** [comment]
thanks.
it is my fault, after adding externals, everything is OK.
