### ISSUE TITLE
invalid :foreign-libs in deps.cljs of  m2/repository/org/omcljs/om/1.0.0-alpha28/om-1.0.0-alpha28.jar

### ISSUE THREAD

**Issue by jobez** [thheller/shadow-build#29]
Hi Thomas,

Hope all is well. I just tried upgrading and am hitting a bug with a build that includes om-1.0.0-alpha28.

Seems this function isnt handling the case where the hashmap does not have this field at all.
![shadowerror](https://cloud.githubusercontent.com/assets/615197/12438422/71819f46-bedb-11e5-9a0a-3dffb84b8ef8.gif)

**Comment by thheller** [comment]
Fixed in `[thheller/shadow-build "1.0.199"]`.

Already worked around this one once, om is odd that is ships externs but provides no foreign-libs. I think this only was a workaround for invalid externs in cljsjs/react which was fixed a while ago [2]. 

[1] https://github.com/thheller/shadow-build/blob/a94b5a3f4a732bec429dc150e46d3a5de73d647b/src/clj/shadow/cljs/build.clj#L357-L360
[2] https://github.com/cljsjs/packages/commit/969d6ec04638efdb4e5879e58421632a70793383

**Comment by thheller** [comment]
Also pushed `[thheller/shadow-build "1.0.201"]` which replaces the problematic `load-externs`. It should now log which externs are used to make it easier to spot missing externs.

Please try this version. It should be more reliable overall.

**Comment by jobez** [comment]
Greatly appreciated my friend!
