### ISSUE TITLE
:node-global-prefix in a REPL environment

### ISSUE THREAD

**Issue by thheller** [thheller/shadow-build#30]
The `:node-global-prefix` was intended as a way to avoid conflicts when 2 `:none` optimized CLJS libraries are running in the same node.js process without any coordination between the two.

Current library A will load its `goog/base.js` and setup its dependencies and starts to `goog.provide` and `goog.require` its world.

Library B will then enter this world and in cause conflicts when trying to `goog.provide` things again that A already provided (as seen in `proton` with `proto-repl` and the `cljs.repl` ns).

`:node-global-prefix` allows to use `global.PREFIX` instead of just `global` as to avoid conflicts.

The downside is that all files need to pull objects from this scope into the local `module` scope.

If everything operates off `global` you can do `goog.provide('cljs.core')` and you'll have a `cljs` object in the `module` scope. Since it will lookup `global.cljs` automatically. It will however not look for `global.PREFIX.cljs`.

So in addition to `goog.provide` with must also setup `goog` first via

```
var goog = global.PREFIX.goog;
goog.provide('cljs.core');
```

For each `goog.require` we must

``` javascript
goog.require('cljs.core');
var cljs = goog.getObjectByName('cljs');
// this is a bit pointless, only need to get the root really
cljs.core = goog.getObjectByName('cljs.core');
```

Currently this is only generated for `.cljs` files, any Closure JS files won't do this setup and REPL code snippets won't do this either. This is problematic since the REPL basically is unusable for anything serious as it will use `global.goog` instead of `global.PREFIX.goog`.

Option A) Instead of emitting the setup code manually for CLJS files use a closure compiler pass to rewrite `goog.provide` and `goog.require` statements to do the additional setup. This would touch the JS and it would work for `.cljs` as well as `.js`

Option B) Ignore it. There really should not be 2 closure libraries in `:none` mode running at the same time. Libraries should ship in at least `:simple` and this would not pollute the global. Investigate why `proto-repl` ships in `:none`, probably because it uses itself as the REPL host.

Option C) Drop `:node-global-prefix`, I don't like having half-baked features that break this easily.

**Comment by pbiggar** [comment]
I've been playing around all day, trying to make the repl work. I'm doing a braindump here - hope that's useful.

I seem to be in Option B above: I'm building two atom plugins at the same time, so both of them are in unoptimized mode. (I disabled one of them to get to the next step, described below).

I tried node-global-prefix and got weird errors. When I first loaded the process, the repl loaded just fine. Then I saved my file causing the program to reload, and this worked fine. However, after this, it stopped working. This turned out to be because my prefix was the same as my namespace (prefix: "global.treecommit", namespace: "treecommit.core"). Maybe a doc update to suggest to use all CAPS for the prefix like proton does.

When I disabled node-global-prefix, repl.js would fail to load. repl.js (and also files like clojure/string.js) start with the line `var goog = global.treecommit.goog;`. I actually don't know why they use "treecommit" here (I don't have a node-global-prefix set).

Anyway, to work around this, I added this line when my program loads:   `(set! js/treecommit.goog js/goog)`. Then when the repl loads, it has global.treecommit.goog available, the new code overwrites global.treecommit, and then the activation added global.treecommit.goog.

I was using a variety of versions, being aware of recent changes to node-global-prefix. I think most of these problems happened on 1.0.209, but I amn't certain.

Hope this is helpful. Thanks for shadow-build, it's incredibly fast and the built-in repl really speeds up developing atom plugins!

**Comment by thheller** [comment]
Thanks for the feedback.

Yes, the `:node-global-prefix` must be something unique. All caps or something like `$treecommit` as the conflict with your namespaces may cause errors in unexpected places.

The files need to be recompiled after you disable `:node-global-prefix`, my cache busting doesn't account for `:node-global-prefix` and won't recompile them by default. Try `rm -rf target/shadow-build` to force the recompile. After the `clojure/string.js` should no longer have the `var goog = global.treecommit.goog;` line.

**Comment by thheller** [comment]
Just pushed `[thheller/shadow-build "1.0.215"]` that should fix the cache issue.

**Comment by pbiggar** [comment]
Fantastic, that fixes it! Thanks!

So to be clear, I shouldn't use `:node-global-prefix`? What should I do if I have two unoptimized libraries in the same process, both using shadow-build? Any safe options?

**Comment by thheller** [comment]
When both builds use a different `:node-global-prefix` you should be fine on the live-reloading front. 

The REPL currently assumes to access just `global` and no other prefix. So if both libs are using a prefix the REPL won't work. If only one build has a `:node-global-prefix` the REPL will look like it is working but code from the build with `:node-global-prefix` will effectively be `eval`'d in the environment of the build without. That will produce some very strange results and basically make the REPL unusable for anything besides `hello world` since it can only access state/code of the other build but not its own.

I have no solution for that yet.

**Comment by thheller** [comment]
In case someone else is still interested in this: `:node-global-prefix` is gone. I rewrote most of the `node` related code generation and it no longer exposes any globals. So there won't be any conflicts anymore.

Not completely finished yet but I wrote down some stuff here [1]. Will release something soon.

[1] https://github.com/thheller/shadow-build/blob/master/doc/node.md
