### ISSUE TITLE
How to use it to generate multiple js files?

### ISSUE THREAD

**Issue by zhiy** [thheller/shadow-build#31]
Is there doc or example use it to generate multiple js files? Like :modules option? I have problems to use modules option, to see whether shallow build can help.

**Comment by thheller** [comment]
Why do `:modules` not work for you?

Modules are actually the default for shadow-build, but they are implemented differently from default CLJS.

Can you describe what you trying to do?

**Comment by zhiy** [comment]
##################
{
                        :id "dev1"
                        :source-paths ["src/cljs"]
                        :compiler {:main "jsapp.core"
                                   :asset-path "static/out"
                                   :output-dir "public/out"
                                   :modules {
                                             :core
                                             {:output-to "public/out/app.js"
                                              :entries #{"jsapp.core"}}
                                             }
                                   :optimizations :simple
                                   :pretty-print true}}
###############################

and I try to include the js in html file:

"/static/out/cljs_base.js"
"/static/out/app.js"

and add js code:
(javascript-tag "goog.require('cljs.core');goog.require('jsapp.core');")
(javascript-tag "jsapp.core.run()")

But it is not working for me, errors like:

cljs_base.js:12 Uncaught TypeError: Cannot read property '__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED' of undefined(anonymous function) @ cljs_base.js:12(anonymous function) @ cljs_base.js:12(anonymous function) @ cljs_base.js:12
app.js:2 Uncaught TypeError: Cannot read property 'core' of undefined(anonymous function) @ app.js:2
search-log:3 Uncaught TypeError: Cannot read property 'require' of undefined(anonymous function) @ search-log:3
search-log:5 Uncaught TypeError: jsapp.core.run is not a function

**Comment by thheller** [comment]
Whenever you use `:simple` it is not required to `goog.require` anything in your HTML.

This explains the `search-log:3 Uncaught TypeError: Cannot read property 'require' of undefined(anonymous function) @ search-log:3` error.

I suspect that this is an issue with CLJS and `:externs` packaging. It seems that `React` is not included since `__SECRET_DOM_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` is a property of the `React` object.

Try the shadow-build-example [1] I mentioned.


As a side not though, why are you trying to split the code into 2 modules if you include both in your page?

In my experience it does not make much sense to split the code unless you have at least some pages that only include one file. Since all your code (`jsapp.core`) is in the `app.js` (which requires `cljs_base.js`) you are basically always loading all code. Unless you have a third module or some code you can use with only `cljs_base.js` don't bother with `:modules` as you'll gain almost nothing.

Bonus tip: Whenever pasting code into GitHub Issues try wrapping it in \`\`\`code\`\`\` for multiple lines or \`code\` for single words/sentences. It makes it look pretty. :)



[1] https://github.com/thheller/shadow-build-example/issues/2#issuecomment-234735784

**Comment by zhiy** [comment]
It is just an example, I will have many js in the project and include in different pages.
Thanks, I will try your example.
